### ISSUE TITLE
require('smtp-tester') doesn't work.  Dependency problem maybe.

### ISSUE THREAD

**Issue by chevin99** [deitch/smtp-tester#14]
I got a script all the way down to nothing but this:

```
'use strict';
let tester = require('smtp-tester')
```

And I get this error:

```
Error: Cannot find module 'libqp'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/me/Documents/my-repo/node_modules/smtp-tester/node_modules/mailparser/node_modules/mailsplit/lib/mime-node.js:5:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

It was working yesterday, but stopped working today.  I did notice one of the dependencies `mailparser` had [a release today](https://github.com/andris9/mailparser/releases), so maybe that broke it.

**Comment by chevin99** [comment]
Sorry, I realized my version was locked on 0.5.1, but it's ok after I updated to 0.6.3.  Thanks for your work on this and have a nice day.

**Comment by deitch** [comment]
Hey @chevin99 

heh, I saw the issue, was about to do a clean install in a tmp dir to try and replicate, and if not, ask for your node version and `npm ls` output. But you got it!

> Thanks for your work on this

Pleasure. I am glad my work helped others. What project are you using it for?

**Comment by chevin99** [comment]
@deitch I'm using smtp-tester to test delivery of some billing emails
